// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
//
// If the env vars are missing (e.g. fresh local clone with no `.env`),
// we export a stub client instead of throwing at module load — this lets
// the app boot in Demo Mode instead of showing a blank white screen.

function createStubClient(): SupabaseClient<Database> {
  const notConfigured = async () => ({
    data: null,
    error: { message: 'Supabase is not configured. Create a .env file (see .env.example) or use Demo Mode.' },
  });
  const handler: ProxyHandler<any> = {
    get(_t, prop) {
      if (prop === 'auth') {
        return {
          getSession: async () => ({ data: { session: null }, error: null }),
          onAuthStateChange: () => ({ data: { subscription: { unsubscribe() {} } } }),
          signInWithPassword: notConfigured,
          signUp: notConfigured,
          signOut: async () => ({ error: null }),
        };
      }
      if (prop === 'from' || prop === 'rpc' || prop === 'channel' || prop === 'removeChannel') {
        return () => new Proxy(() => {}, handler);
      }
      if (prop === 'then') return undefined; // not a thenable
      return new Proxy(() => {}, handler);
    },
    apply: () => new Proxy(() => {}, handler),
  };
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return new Proxy(function () {} as any, handler) as SupabaseClient<Database>;
}

export const supabase: SupabaseClient<Database> =
  SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY
    ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
        auth: {
          storage: brokeredPreviewStorage(),
          persistSession: true,
          autoRefreshToken: true,
        },
      })
    : (console.warn(
        '[supabase] VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY missing — running without a backend. Demo Mode only.'
      ),
      createStubClient());
